dataSources:
  ds0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/hmdp
    username: root
    password: mysql
  ds1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3307/hmdp_1
    username: root
    password: mysql

rules:
  - !SHARDING
    tables:
      tb_voucher_order:
        # 分库分表：ds0/ds1 库中各含 tb_voucher_order 表
        actualDataNodes: ds${0..1}.tb_voucher_order
        # 分库策略（按 user_id 路由到不同库）
        databaseStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: db_inline
    shardingAlgorithms:
      # 分库算法：user_id % 2 决定库序号
      db_inline:
        type: INLINE
        props:
          algorithm-expression: ds${user_id % 2}  # 结果取 0 或 1
  - !SINGLE
    tables:
      - "*.*"
    defaultDataSource: ds0
props:
  sql-show: true